version: '3'
services:
  ativos-app-backend:
    container_name: "ativos-api"
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    image: ativos-api
    # env_file: .env
    restart: on-failure
    ports:
      - "8181:8181"
      - "8080:8080"
    environment:
      - API_PORT=8080
      - STREAMLIT_SERVER_PORT=8181
    deploy:
        resources:
            limits:
              cpus: "0.50"
              memory: 256M
            reservations:
              memory: 128M
  # ativos-app-frontend:
  #     container_name: "ativos-frontend"
  #     build:
  #       context: ./
  #       dockerfile: ./docker/frontend/Dockerfile
  #     image: ativos-frontend
  #     # env_file: .env
  #     restart: on-failure
  #     ports:
  #       - "8081:8081"
  #       - "8080:8080"
  #     environment:
  #       - API_PORT=8080
  #     deploy:
  #         resources:
  #             limits:
  #               cpus: "0.50"
  #               memory: 256M
 
