version: '3'
services:
  ativos-app-backend:
    container_name: "ativos-api"
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    image: ativos-api
    # env_file: .env
    restart: on-failure
    ports:
      - "8181:8181"
      - "8282:8282"
    environment:
      - API_PORT=8282
      - STREAMLIT_SERVER_PORT=8181
    deploy:
        resources:
            limits:
              cpus: "0.50"
              memory: 256M
            reservations:
              memory: 128M
    networks:
      - ativos-network
  ativos-app-frontend:
      container_name: "ativos-frontend"
      build:
        context: ./
        dockerfile: ./docker/frontend/Dockerfile
      image: ativos-frontend
      # env_file: .env
      restart: on-failure
      ports:
        - "80:80"
      environment:
        - API_HOST=ativos-app-backend
        - API_PORT=8282
      depends_on:
        - ativos-app-backend
      deploy:
          resources:
              limits:
                cpus: "1"
                memory: 512M
              reservations:
                memory: 512M
      networks:
      - ativos-network
networks:
  ativos-network:
    driver: bridge
 
